---
language: ruby
rvm:
- 2.1.0
env:
- PATH=/usr/games:$PATH
before_install:
- sudo service postgresql stop
- sudo service mysql stop
- sudo apt-get update
- sudo apt-get -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold"
  dist-upgrade
- sudo add-apt-repository ppa:ecere-team/ppa -y
- sudo add-apt-repository ppa:directhex/ppa -y
- sudo apt-get update
- sudo apt-get -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold"
  dist-upgrade
- 'sudo apt-get install afnix              #  1 / 86'
- 'sudo apt-get install algol68g           #  2 / 86'
- 'sudo apt-get install aplus-fsf          #  3 / 86'
- 'sudo apt-get install asymptote          #  4 / 86'
- 'sudo apt-get install ats-lang-anairiats #  5 / 86'
- 'sudo apt-get install bash               #  6 / 86'
- 'sudo apt-get install bc                 #  7 / 86'
- 'sudo apt-get install bf                 #  8 / 86'
- 'sudo apt-get install boo                #  9 / 86'
- 'sudo apt-get install bsdgames           # 10 / 86'
- 'sudo apt-get install cduce              # 11 / 86'
- 'sudo apt-get install clisp              # 12 / 86'
- 'sudo apt-get install clojure            # 13 / 86'
- 'sudo apt-get install cmake              # 14 / 86'
- 'sudo apt-get install coffeescript       # 15 / 86'
- 'sudo apt-get install dc                 # 16 / 86'
- 'sudo apt-get install ecere-sdk          # 17 / 86'
- 'sudo apt-get install emacs23            # 18 / 86'
- 'sudo apt-get install erlang             # 19 / 86'
- 'sudo apt-get install f2c                # 20 / 86'
- 'sudo apt-get install falconpl           # 21 / 86'
- 'sudo apt-get install fp-compiler        # 22 / 86'
- 'sudo apt-get install fsharp             # 23 / 86'
- 'sudo apt-get install g++                # 24 / 86'
- 'sudo apt-get install gambas2-script     # 25 / 86'
- 'sudo apt-get install gap                # 26 / 86'
- 'sudo apt-get install gauche             # 27 / 86'
- 'sudo apt-get install gawk               # 28 / 86'
- 'sudo apt-get install gcc                # 29 / 86'
- 'sudo apt-get install gdc                # 30 / 86'
- 'sudo apt-get install genius             # 31 / 86'
- 'sudo apt-get install gforth             # 32 / 86'
- 'sudo apt-get install gfortran           # 33 / 86'
- 'sudo apt-get install ghc                # 34 / 86'
- 'sudo apt-get install ghostscript        # 35 / 86'
- 'sudo apt-get install gnat               # 36 / 86'
- 'sudo apt-get install gnu-smalltalk      # 37 / 86'
- 'sudo apt-get install gnuplot            # 38 / 86'
- 'sudo apt-get install gobjc              # 39 / 86'
- 'sudo apt-get install golang             # 40 / 86'
- 'sudo apt-get install groff              # 41 / 86'
- 'sudo apt-get install groovy             # 42 / 86'
- 'sudo apt-get install icont              # 43 / 86'
- 'sudo apt-get install iconx              # 44 / 86'
- 'sudo apt-get install intercal           # 45 / 86'
- 'sudo apt-get install iverilog           # 46 / 86'
- 'sudo apt-get install jasmin-sable       # 47 / 86'
- 'sudo apt-get install libgd2-xpm-dev     # 48 / 86'
- 'sudo apt-get install libpng12-dev       # 49 / 86'
- 'sudo apt-get install llvm               # 50 / 86'
- 'sudo apt-get install lua5.2             # 51 / 86'
- 'sudo apt-get install make               # 52 / 86'
- 'sudo apt-get install maxima             # 53 / 86'
- 'sudo apt-get install mlton              # 54 / 86'
- 'sudo apt-get install mono-devel         # 55 / 86'
- 'sudo apt-get install mono-mcs           # 56 / 86'
- 'sudo apt-get install mono-vbnc          # 57 / 86'
- 'sudo apt-get install nasm               # 58 / 86'
- 'sudo apt-get install neko               # 59 / 86'
- 'sudo apt-get install nickle             # 60 / 86'
- 'sudo apt-get install ocaml              # 61 / 86'
- 'sudo apt-get install octave             # 62 / 86'
- 'sudo apt-get install open-cobol         # 63 / 86'
- 'sudo apt-get install openjdk-6-jdk      # 64 / 86'
- 'sudo apt-get install pari-gp            # 65 / 86'
- 'sudo apt-get install parrot             # 66 / 86'
- 'sudo apt-get install perl               # 67 / 86'
- 'sudo apt-get install php5-cli           # 68 / 86'
- 'sudo apt-get install pike7.8            # 69 / 86'
- 'sudo apt-get install python             # 70 / 86'
- 'sudo apt-get install r-base             # 71 / 86'
- 'sudo apt-get install ratfor             # 72 / 86'
- 'sudo apt-get install regina-rexx        # 73 / 86'
- 'sudo apt-get install rhino              # 74 / 86'
- 'sudo apt-get install scala              # 75 / 86'
- 'sudo apt-get install scilab             # 76 / 86'
- 'sudo apt-get install slsh               # 77 / 86'
- 'sudo apt-get install spl-core           # 78 / 86'
- 'sudo apt-get install swi-prolog         # 79 / 86'
- 'sudo apt-get install tcc                # 80 / 86'
- 'sudo apt-get install tcl                # 81 / 86'
- 'sudo apt-get install ucblogo            # 82 / 86'
- 'sudo apt-get install valac              # 83 / 86'
- 'sudo apt-get install xsltproc           # 84 / 86'
- 'sudo apt-get install yorick             # 85 / 86'
- 'sudo apt-get install zoem               # 86 / 86'
before_script:
- make -C vendor/
script:
- make CC=tcc
