---
language: ruby
rvm:
- 2.1.0
env:
- PATH=/usr/games:$PATH
before_install:
- sudo service postgresql stop
- sudo service mysql stop
- sudo apt-get remove postgresql-9.3 -y
- sudo apt-get update
- sudo apt-get -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold"
  dist-upgrade
- sudo add-apt-repository ppa:ecere-team/ppa -y
- sudo add-apt-repository ppa:directhex/ppa -y
- sudo apt-get update
- sudo apt-get -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold"
  dist-upgrade
- 'sudo apt-get install afnix              #  1 / 88'
- 'sudo apt-get install algol68g           #  2 / 88'
- 'sudo apt-get install aplus-fsf          #  3 / 88'
- 'sudo apt-get install asymptote          #  4 / 88'
- 'sudo apt-get install ats-lang-anairiats #  5 / 88'
- 'sudo apt-get install bash               #  6 / 88'
- 'sudo apt-get install bc                 #  7 / 88'
- 'sudo apt-get install bf                 #  8 / 88'
- 'sudo apt-get install boo                #  9 / 88'
- 'sudo apt-get install bsdgames           # 10 / 88'
- 'sudo apt-get install cduce              # 11 / 88'
- 'sudo apt-get install clisp              # 12 / 88'
- 'sudo apt-get install clojure            # 13 / 88'
- 'sudo apt-get install cmake              # 14 / 88'
- 'sudo apt-get install coffeescript       # 15 / 88'
- 'sudo apt-get install dc                 # 16 / 88'
- 'sudo apt-get install ecere-sdk          # 17 / 88'
- 'sudo apt-get install emacs23            # 18 / 88'
- 'sudo apt-get install erlang             # 19 / 88'
- 'sudo apt-get install f2c                # 20 / 88'
- 'sudo apt-get install falconpl           # 21 / 88'
- 'sudo apt-get install fp-compiler        # 22 / 88'
- 'sudo apt-get install fsharp             # 23 / 88'
- 'sudo apt-get install g++                # 24 / 88'
- 'sudo apt-get install gambas2-script     # 25 / 88'
- 'sudo apt-get install gap                # 26 / 88'
- 'sudo apt-get install gauche             # 27 / 88'
- 'sudo apt-get install gawk               # 28 / 88'
- 'sudo apt-get install gcc                # 29 / 88'
- 'sudo apt-get install gdc                # 30 / 88'
- 'sudo apt-get install genius             # 31 / 88'
- 'sudo apt-get install gforth             # 32 / 88'
- 'sudo apt-get install gfortran           # 33 / 88'
- 'sudo apt-get install ghc                # 34 / 88'
- 'sudo apt-get install ghostscript        # 35 / 88'
- 'sudo apt-get install gnat               # 36 / 88'
- 'sudo apt-get install gnu-smalltalk      # 37 / 88'
- 'sudo apt-get install gnuplot            # 38 / 88'
- 'sudo apt-get install gobjc              # 39 / 88'
- 'sudo apt-get install golang             # 40 / 88'
- 'sudo apt-get install gpt                # 41 / 88'
- 'sudo apt-get install gri                # 42 / 88'
- 'sudo apt-get install groff              # 43 / 88'
- 'sudo apt-get install groovy             # 44 / 88'
- 'sudo apt-get install icont              # 45 / 88'
- 'sudo apt-get install iconx              # 46 / 88'
- 'sudo apt-get install intercal           # 47 / 88'
- 'sudo apt-get install iverilog           # 48 / 88'
- 'sudo apt-get install jasmin-sable       # 49 / 88'
- 'sudo apt-get install libgd2-xpm-dev     # 50 / 88'
- 'sudo apt-get install libpng12-dev       # 51 / 88'
- 'sudo apt-get install llvm               # 52 / 88'
- 'sudo apt-get install lua5.2             # 53 / 88'
- 'sudo apt-get install make               # 54 / 88'
- 'sudo apt-get install maxima             # 55 / 88'
- 'sudo apt-get install mlton              # 56 / 88'
- 'sudo apt-get install mono-devel         # 57 / 88'
- 'sudo apt-get install mono-mcs           # 58 / 88'
- 'sudo apt-get install mono-vbnc          # 59 / 88'
- 'sudo apt-get install nasm               # 60 / 88'
- 'sudo apt-get install neko               # 61 / 88'
- 'sudo apt-get install nickle             # 62 / 88'
- 'sudo apt-get install ocaml              # 63 / 88'
- 'sudo apt-get install octave             # 64 / 88'
- 'sudo apt-get install open-cobol         # 65 / 88'
- 'sudo apt-get install openjdk-6-jdk      # 66 / 88'
- 'sudo apt-get install pari-gp            # 67 / 88'
- 'sudo apt-get install parrot             # 68 / 88'
- 'sudo apt-get install perl               # 69 / 88'
- 'sudo apt-get install php5-cli           # 70 / 88'
- 'sudo apt-get install pike7.8            # 71 / 88'
- 'sudo apt-get install python             # 72 / 88'
- 'sudo apt-get install r-base             # 73 / 88'
- 'sudo apt-get install ratfor             # 74 / 88'
- 'sudo apt-get install regina-rexx        # 75 / 88'
- 'sudo apt-get install rhino              # 76 / 88'
- 'sudo apt-get install scala              # 77 / 88'
- 'sudo apt-get install scilab             # 78 / 88'
- 'sudo apt-get install slsh               # 79 / 88'
- 'sudo apt-get install spl-core           # 80 / 88'
- 'sudo apt-get install swi-prolog         # 81 / 88'
- 'sudo apt-get install tcc                # 82 / 88'
- 'sudo apt-get install tcl                # 83 / 88'
- 'sudo apt-get install ucblogo            # 84 / 88'
- 'sudo apt-get install valac              # 85 / 88'
- 'sudo apt-get install xsltproc           # 86 / 88'
- 'sudo apt-get install yorick             # 87 / 88'
- 'sudo apt-get install zoem               # 88 / 88'
before_script:
- make -C vendor/
script:
- make CC=tcc
