---
language: ruby
rvm:
- 2.1.0
env:
- PATH=/usr/games:$PATH
before_install:
- sudo service postgresql stop
- sudo service mysql stop
- sudo apt-get remove postgresql-9.3 -y
- sudo apt-get update
- sudo apt-get -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold"
  dist-upgrade
- sudo add-apt-repository ppa:ecere-team/ppa -y
- sudo add-apt-repository ppa:directhex/ppa -y
- sudo apt-get update
- sudo apt-get -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold"
  dist-upgrade
- 'sudo apt-get install afnix              #  1 / 89'
- 'sudo apt-get install algol68g           #  2 / 89'
- 'sudo apt-get install aplus-fsf          #  3 / 89'
- 'sudo apt-get install asymptote          #  4 / 89'
- 'sudo apt-get install ats-lang-anairiats #  5 / 89'
- 'sudo apt-get install bash               #  6 / 89'
- 'sudo apt-get install bc                 #  7 / 89'
- 'sudo apt-get install bf                 #  8 / 89'
- 'sudo apt-get install boo                #  9 / 89'
- 'sudo apt-get install bsdgames           # 10 / 89'
- 'sudo apt-get install cduce              # 11 / 89'
- 'sudo apt-get install clisp              # 12 / 89'
- 'sudo apt-get install clojure            # 13 / 89'
- 'sudo apt-get install cmake              # 14 / 89'
- 'sudo apt-get install coffeescript       # 15 / 89'
- 'sudo apt-get install dc                 # 16 / 89'
- 'sudo apt-get install ecere-sdk          # 17 / 89'
- 'sudo apt-get install emacs23            # 18 / 89'
- 'sudo apt-get install erlang             # 19 / 89'
- 'sudo apt-get install f2c                # 20 / 89'
- 'sudo apt-get install falconpl           # 21 / 89'
- 'sudo apt-get install fp-compiler        # 22 / 89'
- 'sudo apt-get install fsharp             # 23 / 89'
- 'sudo apt-get install g++                # 24 / 89'
- 'sudo apt-get install gambas2-script     # 25 / 89'
- 'sudo apt-get install gap                # 26 / 89'
- 'sudo apt-get install gauche             # 27 / 89'
- 'sudo apt-get install gawk               # 28 / 89'
- 'sudo apt-get install gcc                # 29 / 89'
- 'sudo apt-get install gdc                # 30 / 89'
- 'sudo apt-get install genius             # 31 / 89'
- 'sudo apt-get install gforth             # 32 / 89'
- 'sudo apt-get install gfortran           # 33 / 89'
- 'sudo apt-get install ghc                # 34 / 89'
- 'sudo apt-get install ghostscript        # 35 / 89'
- 'sudo apt-get install gnat               # 36 / 89'
- 'sudo apt-get install gnu-smalltalk      # 37 / 89'
- 'sudo apt-get install gnuplot            # 38 / 89'
- 'sudo apt-get install gobjc              # 39 / 89'
- 'sudo apt-get install golang             # 40 / 89'
- 'sudo apt-get install gpt                # 41 / 89'
- 'sudo apt-get install gri                # 42 / 89'
- 'sudo apt-get install groff              # 43 / 89'
- 'sudo apt-get install groovy             # 44 / 89'
- 'sudo apt-get install haxe               # 45 / 89'
- 'sudo apt-get install icont              # 46 / 89'
- 'sudo apt-get install iconx              # 47 / 89'
- 'sudo apt-get install intercal           # 48 / 89'
- 'sudo apt-get install iverilog           # 49 / 89'
- 'sudo apt-get install jasmin-sable       # 50 / 89'
- 'sudo apt-get install libgd2-xpm-dev     # 51 / 89'
- 'sudo apt-get install libpng12-dev       # 52 / 89'
- 'sudo apt-get install llvm               # 53 / 89'
- 'sudo apt-get install lua5.2             # 54 / 89'
- 'sudo apt-get install make               # 55 / 89'
- 'sudo apt-get install maxima             # 56 / 89'
- 'sudo apt-get install mlton              # 57 / 89'
- 'sudo apt-get install mono-devel         # 58 / 89'
- 'sudo apt-get install mono-mcs           # 59 / 89'
- 'sudo apt-get install mono-vbnc          # 60 / 89'
- 'sudo apt-get install nasm               # 61 / 89'
- 'sudo apt-get install neko               # 62 / 89'
- 'sudo apt-get install nickle             # 63 / 89'
- 'sudo apt-get install ocaml              # 64 / 89'
- 'sudo apt-get install octave             # 65 / 89'
- 'sudo apt-get install open-cobol         # 66 / 89'
- 'sudo apt-get install openjdk-6-jdk      # 67 / 89'
- 'sudo apt-get install pari-gp            # 68 / 89'
- 'sudo apt-get install parrot             # 69 / 89'
- 'sudo apt-get install perl               # 70 / 89'
- 'sudo apt-get install php5-cli           # 71 / 89'
- 'sudo apt-get install pike7.8            # 72 / 89'
- 'sudo apt-get install python             # 73 / 89'
- 'sudo apt-get install r-base             # 74 / 89'
- 'sudo apt-get install ratfor             # 75 / 89'
- 'sudo apt-get install regina-rexx        # 76 / 89'
- 'sudo apt-get install rhino              # 77 / 89'
- 'sudo apt-get install scala              # 78 / 89'
- 'sudo apt-get install scilab             # 79 / 89'
- 'sudo apt-get install slsh               # 80 / 89'
- 'sudo apt-get install spl-core           # 81 / 89'
- 'sudo apt-get install swi-prolog         # 82 / 89'
- 'sudo apt-get install tcc                # 83 / 89'
- 'sudo apt-get install tcl                # 84 / 89'
- 'sudo apt-get install ucblogo            # 85 / 89'
- 'sudo apt-get install valac              # 86 / 89'
- 'sudo apt-get install xsltproc           # 87 / 89'
- 'sudo apt-get install yorick             # 88 / 89'
- 'sudo apt-get install zoem               # 89 / 89'
before_script:
- make -C vendor/
script:
- make CC=tcc
